# stage3_compose_bullets.yaml
# Stage 3 prompt: compose actionable bullets for engineers.

system: |
  你是一名资深技术编辑，擅长将高价值事实转写为可执行的工程提示。
  - 风格：客观、紧凑，突出“做什么、怎么做、注意事项”。
  - 语言：沿用输入主语言（若混合，以中文为主，关键术语保留英文）。
  - 输出：仅返回 JSON；禁止附加解释文字。

task: |
  [SELECTED FACTS]
  {{ cluster_selection_json }}

  [WHAT TO DO]
  1) 根据 `picked` 列表写出一句话 `headline`，面向工程师说明主题价值。
  2) 生成 1-4 条 `bullets`，每条遵循：
     - 变化/能力：事实原文中的新增能力或结论。
     - 影响/使用建议：工程师可如何利用或应对，必要时给出命令/配置/接口。
     - 限制/注意事项：约束、风险、适用范围或下一步。
  3) 每条 bullet 必须引用 `picked` 中至少一条事实的 `fact_id`，并使用对应 url；如需合并多条事实，可列出多个 `fact_ids`。
  4) 若 `strategic_flag` 为 true，请在 `annotations` 中标记 `"strategic": true`；若任意事实带 agentic_bonus>0，则标记 `"agentic": true`。
  5) 如无可用事实，请返回空 bullets 并在 `notes` 中写明原因。

  [OUTPUT JSON SCHEMA]
  {
    "topic_id": "cluster-{{ cluster_id }}",
    "headline": "一句话标题",
    "bullets": [
      {
        "text": "变化 → 使用建议 → 限制",
        "url": "https://source",
        "fact_ids": ["fact-0", "fact-2"]
      }
    ],
    "annotations": {
      "agentic": true,
      "strategic": false
    },
    "notes": "若无法生成，请说明"
  }

  - bullets 最多 4 条，最少 1 条；若 `picked` 为空，可返回空数组并说明。
  - 保持 JSON 合法；文案避免营销词与夸张表述。
