
services:
  rsshub:
    image: diygod/rsshub:latest
    restart: unless-stopped
    ports:
      - "1200:1200"
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: "redis://redis:6379/"
      PUPPETEER_WS_ENDPOINT: "ws://browserless:3000"
      
      # 缓存配置 - 针对 Twitter 优化
      CACHE_EXPIRE: 1800        # 30分钟缓存
      CACHE_CONTENT_EXPIRE: 3600 # 1小时内容缓存
      
      # Twitter 认证 - 关键配置
      TWITTER_USERNAME: '${TWITTER_USERNAME}' # 使用环境变量
      TWITTER_PASSWORD: '${TWITTER_PASSWORD}' # 使用环境变量
    depends_on:
      - redis
      - browserless
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1200/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5

  browserless:
    image: browserless/chrome:latest
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

  tei:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
    restart: unless-stopped
    profiles:
      - tei
    environment:
      MODEL_ID: ${TEI_MODEL_ID}
      HF_TOKEN: ${HF_TOKEN:-}
      HF_HUB_ENABLE_HF_TRANSFER: "1"
      MAX_CONCURRENT_REQUESTS: ${TEI_MAX_CONCURRENT_REQUESTS:-256}
    ports:
      - "127.0.0.1:8080:3000"
    volumes:
      - models-cache:/root/.cache/huggingface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 10

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
      target: production  # 明确指定使用生产阶段
    restart: "no"
    depends_on:
      - rsshub
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - models-cache:/home/appuser/.cache/huggingface  # 修正缓存路径到非root用户
      - logs:/workspace/logs
    env_file: .env
    command: sleep infinity
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  redis-data: {}
  models-cache: {}  # HuggingFace 模型缓存（BGE-Reranker 2.27GB）
  logs: {}
