briefing_id: "example_id"
briefing_title: "示例简报标题"

source:
  type: "rss"
  urls:
    - "https://example.com/feed.xml"

processing:
  time_window_hours: 24
  min_cluster_size: 3
  sim_near_dup: 0.9
  reranker_model: "BAAI/bge-reranker-v2-m3"
  initial_topk: 1000
  max_candidates_per_cluster: 300

summarization:
  prompt_file: "prompts/daily_briefing_multisource.yaml"
  temperature: 0.2
  timeout: 600
  retries: 1
  provider_options:
    openai:
      base_url: "${OPENAI_BASE_URL}"
      # http_proxy: "http://127.0.0.1:7890"
      # https_proxy: "http://127.0.0.1:7890"
    gemini:
      # use_vertex: true
      # project: "your-gcp-project-id"
      # location: "us-central1"
      api_version: "v1"
    ollama:
      host: "http://127.0.0.1:11434"
  llm_provider: "gemini"       # gemini | ollama
  gemini_model: "gemini-2.5-flash"
  ollama_model: "qwen2.5:7b-instruct"
  target_item_count: 10

output:
  dir: "out/example_id"
  formats: ["md", "json"]
  telegram:
    enabled: false
    chat_id: ""
    parse_mode: "None"         # None|Markdown|MarkdownV2|HTML
    chunk_size: 3500
    bot_token_env: "TELEGRAM_BOT_TOKEN"
  github_backup:
    enabled: false
    repo_url: ""               # 如留空则使用当前仓库已配置的 origin
    repo_dir: "."              # 在此目录执行 git 操作
    branch: "main"
    author_name_env: "GIT_AUTHOR_NAME"
    author_email_env: "GIT_AUTHOR_EMAIL"
    token_env: "GITHUB_TOKEN"
    commit_message_prefix: "briefing"
    pathspec: ""               # 为空时自动使用 output.dir