briefing_id: ai-briefing-hackernews
briefing_title: AI 快讯 · Hacker News
source:
  type: hackernews
  hn_story_type: top
  hn_limit: 60
processing:
  time_window_hours: 24
  min_cluster_size: 3
  sim_near_dup: 0.9
  reranker_model: BAAI/bge-reranker-v2-m3
  initial_topk: 1000
  max_candidates_per_cluster: 300
summarization:
  prompt_file: prompts/daily_briefing_multisource.yaml
  temperature: 0.2
  timeout: 600
  retries: 1
  provider_options:
    openai:
      base_url: ${OPENAI_BASE_URL}
    gemini:
      api_version: v1
  openai_model: gpt-4o-mini
  llm_provider: openai
  gemini_model: gemini-2.5-flash
  target_item_count: 10
output:
  dir: out/ai-briefing-hackernews
  formats:
  - md
  - json
  telegram:
    enabled: true
    chat_id: '@your_channel_or_chat_id'
    parse_mode: None
    chunk_size: 3500
  github_backup:
    enabled: true
    repo_url: https://github.com/yourname/briefing-backup.git
    repo_dir: .
    branch: main
    commit_message_prefix: ai-briefing-hackernews
