briefing_id: ai-briefing-reddit
briefing_title: AI 快讯 · Reddit
source:
  type: reddit
  subreddits:
  - gamedev
  - Unity3D
  sort_by: top
  time_window: day
  limit_per_subreddit: 15
processing:
  time_window_hours: 24
  min_cluster_size: 3
  sim_near_dup: 0.9
  reranker_model: BAAI/bge-reranker-v2-m3
  initial_topk: 1000
  max_candidates_per_cluster: 300
summarization:
  prompt_file: prompts/daily_briefing_multisource.yaml
  temperature: 0.2
  timeout: 600
  retries: 1
  provider_options:
    openai:
      base_url: ${OPENAI_BASE_URL}
    gemini:
      api_version: v1
  openai_model: gpt-4o-mini
  llm_provider: gemini
  gemini_model: gemini-2.5-flash
  target_item_count: 8
output:
  dir: out/ai-briefing-reddit
  formats:
  - md
  telegram:
    enabled: false
    chat_id: ''
    parse_mode: None
    chunk_size: 3500
  github_backup:
    enabled: false
    repo_url: ''
    repo_dir: .
    branch: main
    commit_message_prefix: ai-briefing-reddit
