briefing_id: "hackernews_daily"
briefing_title: "Hacker News 每日简报"

source:
  type: "hackernews"
  hn_story_type: "top"    # top | new | best
  hn_limit: 60

processing:
  time_window_hours: 24
  min_cluster_size: 3
  sim_near_dup: 0.90
  reranker_model: "BAAI/bge-reranker-v2-m3"
  initial_topk: 1000
  max_candidates_per_cluster: 300

summarization:
  llm_provider: "ollama"
  gemini_model: "gemini-2.5-flash"
  ollama_model: "qwen2.5:7b-instruct"
  prompt_system: "prompts/system_common.txt"
  prompt_template: "prompts/template_daily.txt"
  target_item_count: 10

output:
  dir: "out/hackernews_daily"
  formats: ["md", "json"]
  telegram:
    enabled: true
    chat_id: "@your_channel_or_chat_id"
    parse_mode: "None"
    chunk_size: 3500
  github_backup:
    enabled: true
    repo_url: "https://github.com/yourname/briefing-backup.git"
    repo_dir: "."
    branch: "main"
    commit_message_prefix: "hn-daily"