briefing_id: "reddit_gamedev"
briefing_title: "游戏开发 Reddit 精华"

source:
  type: "reddit"
  subreddits:
    - "gamedev"
    - "Unity3D"
  sort_by: "top"
  time_window: "day"
  limit_per_subreddit: 15

processing:
  time_window_hours: 24
  min_cluster_size: 3
  sim_near_dup: 0.90
  reranker_model: "BAAI/bge-reranker-v2-m3"
  initial_topk: 1000
  max_candidates_per_cluster: 300

summarization:
  llm_provider: "ollama"
  gemini_model: "gemini-2.5-flash"
  ollama_model: "llama3.1:8b-instruct"
  prompt_system: "prompts/system_common.txt"
  prompt_template: "prompts/template_daily.txt"
  target_item_count: 8

output:
  dir: "out/reddit_gamedev"
  formats: ["md"]
  telegram:
    enabled: false
    chat_id: ""
    parse_mode: "None"
    chunk_size: 3500
  github_backup:
    enabled: false
    repo_url: ""
    repo_dir: "."
    branch: "main"
    commit_message_prefix: "reddit-gamedev"