briefing_id: "twitter_dev_tools"
briefing_title: "开发者工具前沿简报"

source:
  type: "twitter_list"
  id: "1933036352834281792"   # Twitter List ID

processing:
  time_window_hours: 24
  min_cluster_size: 2
  sim_near_dup: 0.92
  reranker_model: "BAAI/bge-reranker-v2-m3"
  initial_topk: 1000
  max_candidates_per_cluster: 300

summarization:
  prompt_file: "prompts/daily_briefing_multisource.yaml"
  temperature: 0.2
  timeout: 600
  retries: 1
  provider_options:
    openai:
      base_url: "${OPENAI_BASE_URL}"
      # http_proxy: "http://127.0.0.1:7890"
      # https_proxy: "http://127.0.0.1:7890"
    gemini:
      # use_vertex: true
      # project: "your-gcp-project-id"
      # location: "us-central1"
      api_version: "v1"
    ollama:
      host: "http://127.0.0.1:11434"
  openai_model: "gpt-4o-mini"
  llm_provider: "gemini"
  gemini_model: "gemini-2.5-flash"
  ollama_model: "qwen2.5:7b-instruct"
  target_item_count: 10

output:
  dir: "out/twitter_dev_tools"
  formats: ["md", "json"]
  telegram:
    enabled: false
    chat_id: ""
    parse_mode: "None"
    chunk_size: 3500
  github_backup:
    enabled: false
    repo_url: ""
    repo_dir: "."
    branch: "main"
    commit_message_prefix: "twitter-dev-tools"