briefing_id: "twitter_dev_tools"
briefing_title: "开发者工具前沿简报"

source:
  type: "twitter_list"
  id: "1933036352834281792"   # Twitter List ID

processing:
  time_window_hours: 24
  min_cluster_size: 2
  sim_near_dup: 0.92
  reranker_model: "BAAI/bge-reranker-v2-m3"
  initial_topk: 1000
  max_candidates_per_cluster: 300

summarization:
  llm_provider: "gemini"
  gemini_model: "gemini-2.5-flash"
  ollama_model: "qwen2.5:7b-instruct"
  prompt_system: "prompts/system_common.txt"
  prompt_template: "prompts/template_daily.txt"
  target_item_count: 10

output:
  dir: "out/twitter_dev_tools"
  formats: ["md", "json"]
  telegram:
    enabled: false
    chat_id: ""
    parse_mode: "None"
    chunk_size: 3500
  github_backup:
    enabled: false
    repo_url: ""
    repo_dir: "."
    branch: "main"
    commit_message_prefix: "twitter-dev-tools"